repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.74.1

  hooks:
  - id: terraform_fmt
  - id: terraform_validate
  - id: terraform_tflint
    args:
    - --args=--config=./.tflint.hcl
    - --args=--module
  - id: terraform_docs
    args:
    - --args=--config=./.tfdocs.yml